---
title: "L3. " 
subtitle: "  "
author: Minseop Lee(Programs in Cognitive Science, SNU)
date: 2022-09-20(Tue)
format:
  revealjs: 
    slide-number: true
    # scrollable: true
    chalkboard: 
      buttons: false
    preview-links: auto
    css: styles.css
    footer: UX와 서비스 기획
resources:
  - demo.pdf
---

### 강의 목표

- 진화에 유용한 모듈구조에 대해 이해한다.
- 서비스를 모듈적 구조로 만들기 위한 역사와 유용성에 대해 이해한다.


---

### 지난 강의 정리

::: incremental
- 성공적인 서비스를 찾고/만들기 위해서는 적절한 exploitation/exploration을 찾아야한다.
- 서비스가 성공하기 위해서는 어느정도 인간의 사회적/인지적 자원을 활용해야 하며 인간에게 부정적인 영향을 줄 수도 있음을 파악하였음.
:::

---

### J2. 경험을 해체한다는 것의 의미

- 서비스의 경험을 pre, during, post 로 분해
- 각각의 경험을 또 더 작은 경험소로 분해

---

### 경험을 해체해야 하는 이유

- 해당 경험에 매칭되는 서비스의 부분 부분을 나누어 기획하고, 만들고, 테스트 하기 위함.
- 각각의 경험이 총체적인 사용자 경험에 어떤 영향을 얼만큼 주는지 확인해야함.
- 서로가 독립적인 영향을 주는 구조체임을 이해해야함.(사용자의 머리속에 경험방이 따로따로 있다고 생각해보자)

-> 모듈성에 대한 이해

---

### 강의 순서

1. 모듈성 개념과 자연계에서 모듈성이 나타나는 방식 

2. 인공물과 서비스에서 모듈성의 유용성과 나타나는 방식


---

### 모듈성이란 무엇인가?


---

### 생물은 유전자의 모듈 구조를 어떻게 활용하는가?

- 이보디보(hox 유전자)
- 대량모듈가설과 진화심리학

---

## 진화생물학에서의 Merge 과정

```{mermaid}
%%| fig-width: 10
    flowchart RL;
      3((9817e0))-->1((e137e9));
      4((ae3e0f))-->3;
      id2(main) -.-> idHead
      id1(HEAD) -.-> id2(main)
      idHead((e2d9e6))-->6;
      idHead-->4;
      5((a1fbcd))-->3;
      52((86d91f))--> 5
      6((711a58))-->52;
      id3(dev) -.-> 6
    
      style id1 fill:#b8dbbc,stroke:#333,stroke-width:1px
      style id2 fill:#f96,stroke:#333,stroke-width:1px
      style id3 fill:#f90,stroke:#333,stroke-width:1px
      style idHead fill:#b8dbbc
```




---

### 진화생물학에서 혁신을 설명하는 법


- 이보디보(Evolutionary Developmental Biology)
- 발생과정이 어떻게 진화했는지에 대해 초점을 맞추는 학문

---

### 진화심리학에서 마음의 구조를 설명하는 법


---


### 강의 순서

1. 모듈성 개념과 자연계에서 모듈성이 나타나는 방식 

2. 인공물과 서비스에서 모듈성의 유용성과 나타나는 방식

---

### 서비스에서 나타나는 모듈성

- 객체지향형 프로그래밍
- 객체지향형 디자인


---

### 객체지향형 프로그래밍의 발전



---

### 객체지향형 디자인의 발전 



---

### 사례

